# -*- coding: utf-8 -*-
"""Text Detection (210526).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16jaeZXADa9FWfOSfvvYhqzh6OZJWbVMN
"""

### 1) Mount Google Drive ###

from google.colab import drive

drive.mount('/content/gdrive')

### 2) Prepare Data ###

!scp '/content/gdrive/My Drive/TextDetector/data.zip' '/content/data.zip'

!unzip '/content/data.zip' -d '/content/'

### 3) Install Dependencies ###

!apt install tesseract-ocr ### Tesseract OCR engine, tool that can read text from images
###contains the compiled OCR binary, language models, OCR inference engine, command-line executable
!apt install libtesseract-dev ### tools/libraries programmers use to interact with it,

!pip install pytesseract ### an interact(bridge) that spawns the Tesseract executable as a subprocess (lets Python talk to the Tesseract engine.)
!pip install Pillow ### image decoding/encoding
!pip install easyocr ### OCR that is different from Tersseract, no external OCR executable needed
!pip install boto3 ### Uses AWS services through APIs, instead of Local CPU. Uses AWS Textract

### 4) Text Detection ###

import pytesseract
from PIL import Image

image_path = '/content/031_red.png'

text = pytesseract.image_to_string(Image.open(image_path),lang='eng')

print(text)

!find /content -name "*.png"

!find /content -name "*.png"